version: "3"
services:
  web:
    image: nginx:1.11.13-alpine
    ports:
        - "80:80"
    depends_on:
      - php
    volumes:
        - /swarm/volumes/opt/php_web_page:/code
        - /swarm/volumes/opt/php_web_page/site.conf:/etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - LEMP
  php:
    image: rohscx/php:7-fpm-alpine-mysqli
    volumes:
        - /swarm/volumes/opt/php_web_page:/code
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - LEMP
  sql:
    image: mariadb:10.1
    volumes:
        - /swarm/volumes/opt/php_web_page/etc/mysql/:/etc/mysql/
        - /swarm/volumes/opt/php_web_page/lib/mysql/:/var/lib/mysql
    env_file:
        - ./mysql.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - LEMP
networks:
  LEMP:
