version: "3"
services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    depends_on:
      - php
    volumes:
        - /swarm/volumes/opt/php_web_page:/code
        - /swarm/volumes/opt/php_web_page/site.conf:/etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
  php:
    image: php:7-fpm-alpine
    volumes:
        - /swarm/volumes/opt/php_web_page:/code
    deploy:
      mode: replicated
      replicas: 1
  sql:
    image: mysql:8
    volumes:
        - /swarm/volumes/opt/php_web_page/mysql/:/etc/mysql/
    deploy:
      mode: replicated
      replicas: 1
