
version: 2
jobs:
  build:
    docker:
      - image: centos/php-56-centos7
    working_directory: /var/www/
    environment:
      BUILD_DIR: /var/www/
    steps:

      # install git
      - run: sudo yum update -y && yum install git -y

      # checkout repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: sudo git submodule sync && sudo git submodule update --init

      - run:
          name: install AWS CLI 
          command: |
            sudo yum makecache
            sudo yum -y install epel-release
            sudo yum makecache
            sudo yum -y install python-pip
            sudo yum clean all
            sudo pip install --upgrade pip
            Sudo pip install awscli
      # Deploy
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $BUILD_DIR s3://your-bucket-name/your-subfolder --delete
            else
              echo "Not master branch, dry run only"
            fi
